import { ThemeConfig, ThemeId } from "./types";

export const THEMES: Record<ThemeId, ThemeConfig> = {
  romantic: {
    id: "romantic",
    name: "Romantic Glow",
    subtitle: "Warm rose pinks & emotional cursive touches",
    description: "Deep blush pinks, soft candlelight glow, and elegant heart animations.",
    badgeColor: "bg-pink-500/20 text-pink-300 border-pink-400/40",
    bgGradient: "from-rose-950 via-pink-900 to-rose-900",
    cardStyle: "bg-rose-950/60 border-rose-500/30 backdrop-blur-xl shadow-rose-900/30",
    accentColor: "from-pink-500 to-rose-600",
    textColor: "text-rose-100",
    subtextColor: "text-pink-200/80",
    fontFamily: "font-serif",
    defaultEffect: "hearts",
    previewImage: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=600&auto=format&fit=crop&q=80",
  },
  elegant: {
    id: "elegant",
    name: "Midnight Luxury",
    subtitle: "Midnight blue, regal gold accents & sparkling stars",
    description: "Refined luxury with shimmering gold typography and sparkling night stars.",
    badgeColor: "bg-amber-500/20 text-amber-300 border-amber-400/40",
    bgGradient: "from-slate-950 via-indigo-950 to-slate-900",
    cardStyle: "bg-slate-900/70 border-amber-400/30 backdrop-blur-xl shadow-amber-900/20",
    accentColor: "from-amber-300 via-amber-400 to-yellow-600",
    textColor: "text-amber-50",
    subtextColor: "text-slate-300/80",
    fontFamily: "font-serif",
    defaultEffect: "stars",
    previewImage: "https://images.unsplash.com/photo-1513151233558-d860c5398176?w=600&auto=format&fit=crop&q=80",
  },
  party: {
    id: "party",
    name: "Colorful Party",
    subtitle: "High energy neon colors, balloons & confetti explosion",
    description: "Bursting with electric neon gradients, festive balloons, and non-stop confetti.",
    badgeColor: "bg-fuchsia-500/20 text-fuchsia-300 border-fuchsia-400/40",
    bgGradient: "from-purple-950 via-fuchsia-950 to-indigo-950",
    cardStyle: "bg-purple-900/60 border-fuchsia-400/40 backdrop-blur-xl shadow-fuchsia-900/40",
    accentColor: "from-fuchsia-500 via-purple-500 to-cyan-400",
    textColor: "text-white",
    subtextColor: "text-fuchsia-200/90",
    fontFamily: "font-display",
    defaultEffect: "confetti",
    previewImage: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600&auto=format&fit=crop&q=80",
  },
  playful: {
    id: "playful",
    name: "Cute & Playful",
    subtitle: "Soft pastel lavender, sunny yellows & floating flowers",
    description: "Whimsical pastel hues, rounded cute typography, and floating blossoms.",
    badgeColor: "bg-purple-400/20 text-purple-200 border-purple-300/40",
    bgGradient: "from-violet-950 via-purple-900 to-pink-950",
    cardStyle: "bg-violet-900/50 border-purple-300/30 backdrop-blur-xl shadow-purple-950/50",
    accentColor: "from-amber-300 via-pink-300 to-purple-400",
    textColor: "text-purple-100",
    subtextColor: "text-purple-200/80",
    fontFamily: "font-sans",
    defaultEffect: "flowers",
    previewImage: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=600&auto=format&fit=crop&q=80",
  },
  minimal: {
    id: "minimal",
    name: "Minimal & Modern",
    subtitle: "Sleek dark glassmorphism & subtle particle glow",
    description: "Understated elegance with ultra-clean typography, subtle dark gradients, and fireworks.",
    badgeColor: "bg-cyan-500/20 text-cyan-300 border-cyan-400/40",
    bgGradient: "from-zinc-950 via-slate-950 to-zinc-900",
    cardStyle: "bg-zinc-900/70 border-zinc-700/50 backdrop-blur-2xl shadow-black/60",
    accentColor: "from-cyan-400 via-teal-300 to-emerald-400",
    textColor: "text-zinc-100",
    subtextColor: "text-zinc-400",
    fontFamily: "font-sans",
    defaultEffect: "fireworks",
    previewImage: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&auto=format&fit=crop&q=80",
  },
};
